[project]
name = "influxdb-crud-lambda"
version = "1.0.0"
description = "AWS Lambda CRUD API for InfluxDB time-series data"
requires-python = ">=3.11"
dependencies = [
    "urllib3>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
