#!/bin/bash
# Quick reference for testing the InfluxDB CRUD API

echo "================================================"
echo "InfluxDB CRUD API - Quick Test Guide"
echo "================================================"
echo ""
echo "1. Find your ALB DNS:"
echo "   ./scripts/get-alb-dns.sh"
echo ""
echo "2. Check deployment status:"
echo "   ./scripts/check-deployment-status.sh"
echo ""
echo "3. Run integration tests:"
echo "   ./scripts/test-api.sh                    # Auto-discover ALB"
echo "   ./scripts/test-api.sh <ALB_DNS>          # Use specific ALB"
echo ""
echo "4. Manual API test:"
echo "   curl http://<ALB_DNS>/health | jq"
echo ""
echo "================================================"
echo "Common Issues"
echo "================================================"
echo ""
echo "• 'Connection refused' errors:"
echo "  → Wait 5-10 min after deployment for InfluxDB to start"
echo "  → Check Lambda can reach InfluxDB (security groups)"
echo ""
echo "• 'AccessDenied' on CloudFormation:"
echo "  → Use: ./scripts/get-alb-dns.sh to find ALB manually"
echo "  → Or check deployment terminal output"
echo ""
echo "• Health check passes but CRUD fails:"
echo "  → InfluxDB instance may not be running"
echo "  → Check EC2 instance status in console"
echo ""
